project/todos/views.py
from flask import render_template, request, redirect, Blueprint
from project.models import Todo
from project import db

todos_blueprint = Blueprint(
    'todos',
    __name__,
    template_folder='templates'
)


@todos_blueprint.route('/', methods=['POST', 'GET'])
def index():
    if request.method == 'POST':
        task_content = request.form['content']
        new_task = Todo(content=task_content)

        try:
            db.session.add(new_task)
            db.session.commit()
            return redirect('/')
        except:
            return 'There was an issue adding your task'

    else:
        tasks = Todo.query.order_by(Todo.date_created).all()
        return render_template('todos/index.html', tasks=tasks)


@todos_blueprint.route('/delete/<int:id>')
def delete(id):
    tasK_to_delete = Todo.query.get_or_404(id)

    try:
        db.session.delete(tasK_to_delete)
        db.session.commit()
        return redirect('/')
    except:
        return 'There was a problem deleting that task.'


@todos_blueprint.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id):
    task = Todo.query.get_or_404(id)

    if request.method == 'POST':
        task.content = request.form['content']

        try:
            db.session.commit()
            return redirect('/')
        except:
            return 'There was an issue updating your task'

    else:
        return render_template('todos/update.html', task=task)

project/todos/templates/todos/index.html
{% extends 'base.html' %}

{% block head %}
<title>Task Master</title>
{% endblock head %}

{% block body %}
<div class="content">
    <h1 style="text-align: center;">Task Master</h1>

    {% if tasks|length < 1 %} <h4 style="text-align: center;">There are no tasks. Create one below!</h1>
        {% else %}
        <table>
            <tr>
                <th>Task</th>
                <th>Added</th>
                <th>Actions</th>
            </tr>
            {% for task in tasks %}
            <tr>
                <td>{{ task.content }}</td>
                <td>{{ task.date_created.date() }}</td>
                <td>
                    <a href="{{ url_for('todos.delete', id=task.id) }}">Delete</a>
                    <br>
                    <a href="{{ url_for('todos.update', id=task.id) }}">Update</a>
                </td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        <div class="form">
            <form action="{{ url_for('todos.index') }}" method="POST">
                <input type="text" name="content" id="content">
                <input type="submit" value="Add Task">
            </form>
        </div>
</div>
{% endblock body %}

project/todos/templates/todos/update.html
{% extends 'base.html' %}

{% block head %}
<title>Task Master</title>
{% endblock head %}

{% block body %}
<div class="content">
    <h1 style="text-align: center;">Update Task</h1>

    <div class="form">
        <form action="{{ url_for('todos.update', id=task.id) }}" method="POST">
            <input type="text" name="content" id="content" value="{{ task.content }}">
            <input type="submit" value="Update">
        </form>
    </div>
</div>
{% endblock body %}